const {
  app,
  BrowserWindow,
  shell,
  desktopCapturer,
  dialog,
  session,
  Menu,
  systemPreferences,
} = require('electron');
const { autoUpdater } = require('electron-updater');
const log = require('electron-log/main');

const fs = require('node:fs');
const http = require('node:http');
const https = require('node:https');
const net = require('node:net');
const path = require('node:path');
const {
  DEFAULT_SERVER_URL,
  getDesktopConfigServerUrl,
  getUpdateBaseUrl,
  normalizeServerUrl,
} = require('./server-url.cjs');
const {
  handleScreenAnnotationRequest,
  setScreenAnnotationCaptureSource,
  setScreenAnnotationOverlayOrigin,
  stopScreenAnnotationOverlay,
} = require('./screen-annotation-overlay.cjs');
const isDev = !app.isPackaged;
const appName = '多媒体高清AI会议平台';
const linuxDesktopName = 'com.uniccmeet.desktop.desktop';

app.setName(appName);

if (process.platform === 'linux') {
  // Keep the Wayland XDG app id / X11 WM_CLASS aligned with the desktop file
  // generated by electron-builder. Without this association Linux desktops can
  // fall back to a generic or missing title-bar/taskbar icon.
  app.setDesktopName(linuxDesktopName);
}

log.initialize();
log.errorHandler.startCatching();
log.eventLogger.startLogging();
Object.assign(console, log.functions);
log.info('[startup]', {
  version: app.getVersion(),
  platform: process.platform,
  arch: process.arch,
  ozonePlatform: process.platform === 'linux' ? 'auto' : undefined,
  desktopSession: process.env.XDG_SESSION_TYPE,
});

const desktopConfig = loadDesktopConfig();
const serverUrl = normalizeServerUrl(
  process.env.UNICCMEET_SERVER_URL ||
    desktopConfig.serverUrl ||
    DEFAULT_SERVER_URL,
);
const updateBaseUrl = getUpdateBaseUrl(serverUrl);
const updateCheckIntervalMs = 6 * 60 * 60 * 1000;

let server;
let mainWindow;
let instantMessagingWindow;
let updateCheckTimer;
let updateDialogOpen = false;
let updateInstallRequested = false;
let localRecordingCaptureRequestExpiresAt = 0;
let inPageDialogSequence = 0;
const activePrivacyDialogs = new Set();

function loadDesktopConfig() {
  const configPath = app.isPackaged
    ? path.join(process.resourcesPath, 'desktop-config.json')
    : path.join(__dirname, '..', 'build', 'desktop-config.json');
  try {
    const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    return { serverUrl: getDesktopConfigServerUrl(config) };
  } catch (error) {
    if (isDev) {
      return {
        serverUrl: DEFAULT_SERVER_URL,
      };
    }
    throw new Error(`Invalid desktop runtime configuration: ${error.message}`, {
      cause: error,
    });
  }
}

function getUpdateFeedUrl() {
  const baseUrl = updateBaseUrl.endsWith('/')
    ? updateBaseUrl
    : `${updateBaseUrl}/`;

  return new URL(`${process.platform}/${process.arch}/`, baseUrl).toString();
}

function getMacInstallerUrl(version) {
  const fileName = `uniccmeet-${version}-macos-${process.arch}.dmg`;

  return new URL(fileName, getUpdateFeedUrl()).toString();
}

async function showInPageDialog(options) {
  if (!mainWindow || mainWindow.isDestroyed()) {
    return null;
  }

  const buttons = Array.isArray(options.buttons) && options.buttons.length > 0
    ? options.buttons
    : ['确定'];
  const defaultId = Number.isInteger(options.defaultId)
    ? options.defaultId
    : 0;
  const cancelId = Number.isInteger(options.cancelId)
    ? options.cancelId
    : 0;
  const dialogId = `uniccmeet-in-page-dialog-${++inPageDialogSequence}`;
  const content = {
    dialogId,
    type: options.type || 'info',
    title: options.title || '',
    message: options.message || '',
    detail: options.detail || '',
    buttons,
    defaultId,
    cancelId,
  };
  const encodedContent = Buffer.from(
    JSON.stringify(content),
    'utf8',
  ).toString('base64');

  const response = await mainWindow.webContents.executeJavaScript(`
    (() => new Promise((resolve) => {
      const contentBytes = Uint8Array.from(
        atob('${encodedContent}'),
        (character) => character.charCodeAt(0),
      );
      const content = JSON.parse(new TextDecoder().decode(contentBytes));
      const overlay = document.createElement('div');
      const panel = document.createElement('div');
      const title = document.createElement('h2');
      const message = document.createElement('p');
      const detail = document.createElement('p');
      const actions = document.createElement('div');
      const accentColor = content.type === 'error'
        ? '#dc2626'
        : content.type === 'warning'
          ? '#d97706'
          : '#1677ff';

      overlay.id = content.dialogId;
      overlay.setAttribute('role', 'dialog');
      overlay.setAttribute('aria-modal', 'true');
      overlay.setAttribute('aria-labelledby', content.dialogId + '-title');
      Object.assign(overlay.style, {
        position: 'fixed',
        inset: '0',
        zIndex: '2147483647',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '24px',
        background: 'rgba(15, 23, 42, 0.56)',
        fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
      });

      Object.assign(panel.style, {
        width: 'min(520px, 100%)',
        padding: '24px',
        borderRadius: '14px',
        borderTop: '4px solid ' + accentColor,
        background: '#ffffff',
        color: '#0f172a',
        boxShadow: '0 24px 64px rgba(15, 23, 42, 0.28)',
      });

      title.id = content.dialogId + '-title';
      title.textContent = content.title;
      Object.assign(title.style, {
        margin: '0 0 12px',
        fontSize: '20px',
        lineHeight: '1.4',
        fontWeight: '700',
      });

      message.textContent = content.message;
      Object.assign(message.style, {
        margin: '0 0 10px',
        fontSize: '16px',
        lineHeight: '1.6',
        fontWeight: '600',
      });

      detail.textContent = content.detail;
      Object.assign(detail.style, {
        margin: '0',
        fontSize: '14px',
        lineHeight: '1.7',
        color: '#475569',
        whiteSpace: 'pre-wrap',
        overflowWrap: 'anywhere',
      });

      Object.assign(actions.style, {
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent: 'flex-end',
        gap: '10px',
        marginTop: '20px',
      });

      let finished = false;
      const finish = (response) => {
        if (finished) {
          return;
        }
        finished = true;
        document.removeEventListener('keydown', handleKeyDown);
        overlay.remove();
        resolve(response);
      };
      const handleKeyDown = (event) => {
        if (event.key === 'Escape') {
          finish(content.cancelId);
        }
      };

      content.buttons.forEach((label, index) => {
        const button = document.createElement('button');
        const isDefault = index === content.defaultId;
        button.type = 'button';
        button.textContent = label;
        Object.assign(button.style, {
          minWidth: '88px',
          padding: '9px 18px',
          border: isDefault ? '0' : '1px solid #cbd5e1',
          borderRadius: '8px',
          background: isDefault ? accentColor : '#ffffff',
          color: isDefault ? '#ffffff' : '#334155',
          fontSize: '14px',
          fontWeight: '600',
          cursor: 'pointer',
        });
        button.addEventListener('click', () => finish(index));
        actions.append(button);

        if (isDefault) {
          queueMicrotask(() => button.focus());
        }
      });

      overlay.addEventListener('click', (event) => {
        if (event.target === overlay) {
          finish(content.cancelId);
        }
      });
      document.addEventListener('keydown', handleKeyDown);

      if (content.title) {
        panel.append(title);
      }
      if (content.message) {
        panel.append(message);
      }
      if (content.detail) {
        panel.append(detail);
      }
      panel.append(actions);
      overlay.append(panel);
      document.body.append(overlay);
    }))();
  `, true);

  return Number.isInteger(response)
    ? { response, checkboxChecked: false }
    : null;
}

function showUpdateDialog(options) {
  if (updateDialogOpen) {
    return Promise.resolve(null);
  }

  updateDialogOpen = true;
  const owner = mainWindow && !mainWindow.isDestroyed()
    ? mainWindow
    : undefined;
  const dialogPromise = process.platform === 'linux'
    ? showInPageDialog(options)
    : owner
      ? dialog.showMessageBox(owner, options)
      : dialog.showMessageBox(options);

  return dialogPromise
    .catch((error) => {
      log.error('[auto-update] failed to show update dialog:', error);
      return null;
    })
    .finally(() => {
      updateDialogOpen = false;
    });
}

function checkForUpdates() {
  if (isDev) {
    return;
  }

  autoUpdater.checkForUpdates().catch((error) => {
    log.error('[auto-update] check failed:', error);
  });
}

function setupAutoUpdater() {
  if (isDev) {
    log.info('[auto-update] skipped in development');
    return;
  }

  const feedUrl = getUpdateFeedUrl();
  autoUpdater.logger = log;
  autoUpdater.autoDownload = false;
  autoUpdater.autoInstallOnAppQuit = true;
  autoUpdater.autoRunAppAfterInstall = true;
  autoUpdater.setFeedURL({
    provider: 'generic',
    url: feedUrl,
  });

  log.info('[auto-update] feed:', feedUrl);

  autoUpdater.on('checking-for-update', () => {
    log.info('[auto-update] checking');
  });

  autoUpdater.on('update-not-available', (info) => {
    log.info('[auto-update] current version is up to date:', info.version);
  });

  autoUpdater.on('update-available', async (info) => {
    log.info('[auto-update] update available:', info.version);
    updateInstallRequested = false;

    if (process.platform === 'darwin') {
      const result = await showUpdateDialog({
        type: 'info',
        title: '发现新版本',
        message: `多媒体高清AI会议平台 ${info.version} 已可用`,
        detail: '当前 macOS 安装包未使用 Developer ID 签名，无法自动重启安装。请下载 DMG，退出应用后手动覆盖安装。',
        buttons: ['稍后', '下载 DMG 安装包'],
        defaultId: 1,
        cancelId: 0,
        noLink: true,
      });

      if (result && result.response === 1) {
        const installerUrl = getMacInstallerUrl(info.version);
        log.info('[auto-update] opening macOS installer:', installerUrl);

        shell.openExternal(installerUrl).catch(async (error) => {
          log.error('[auto-update] failed to open macOS installer:', error);
          await showUpdateDialog({
            type: 'error',
            title: '无法下载安装包',
            message: '未能打开 macOS 安装包下载地址',
            detail: installerUrl,
            buttons: ['确定'],
            defaultId: 0,
            noLink: true,
          });
        });
      }

      return;
    }

    const result = await showUpdateDialog({
      type: 'info',
      title: '发现新版本',
      message: `多媒体高清AI会议平台 ${info.version} 已可用`,
      detail: '是否现在下载更新？下载期间可以继续使用会议平台。',
      buttons: ['稍后', '下载更新'],
      defaultId: 1,
      cancelId: 0,
      noLink: true,
    });

    if (result && result.response === 1) {
      autoUpdater.downloadUpdate().catch((error) => {
        log.error('[auto-update] download failed:', error);
      });
    }
  });

  autoUpdater.on('download-progress', (progress) => {
    log.info(`[auto-update] downloading: ${progress.percent.toFixed(1)}%`);

    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.setProgressBar(Math.max(0, Math.min(1, progress.percent / 100)));
    }
  });

  autoUpdater.on('update-downloaded', async (info) => {
    log.info('[auto-update] update downloaded:', info.version);

    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.setProgressBar(-1);
    }

    const result = await showUpdateDialog({
      type: 'info',
      title: '更新已准备好',
      message: `版本 ${info.version} 已下载完成`,
      detail: '立即重启即可完成安装。未立即重启时，更新会在退出应用后自动安装。',
      buttons: ['稍后重启', '立即重启并安装'],
      defaultId: 1,
      cancelId: 0,
      noLink: true,
    });

    if (result && result.response === 1 && !updateInstallRequested) {
      updateInstallRequested = true;
      log.info('[auto-update] restart and install requested');

      try {
        autoUpdater.quitAndInstall(false, true);
      } catch (error) {
        updateInstallRequested = false;
        log.error('[auto-update] quit and install failed:', error);
        await showUpdateDialog({
          type: 'error',
          title: '无法重启安装更新',
          message: '应用未能启动更新安装程序',
          detail: '请完全退出应用后重新打开并再次检查更新。',
          buttons: ['确定'],
          defaultId: 0,
          noLink: true,
        });
      }
    }
  });

  autoUpdater.on('error', (error) => {
    log.error('[auto-update] updater error:', error);

    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.setProgressBar(-1);
    }
  });

  setTimeout(checkForUpdates, 5000);
  updateCheckTimer = setInterval(checkForUpdates, updateCheckIntervalMs);
}

const macPrivacySettingsUrls = {
  camera:
    'x-apple.systempreferences:com.apple.preference.security?Privacy_Camera',
  microphone:
    'x-apple.systempreferences:com.apple.preference.security?Privacy_Microphone',
  screen:
    'x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture',
};

const macPrivacyLabels = {
  camera: '摄像头',
  microphone: '麦克风',
  screen: '屏幕与系统音频录制',
};

async function openMacPrivacySettings(mediaTypes) {
  const target = mediaTypes.length === 1
    ? macPrivacySettingsUrls[mediaTypes[0]]
    : 'x-apple.systempreferences:com.apple.preference.security';

  try {
    await shell.openExternal(target);
  } catch (error) {
    console.error('[media-permission] failed to open System Settings:', error);
  }
}

async function showMacPrivacyHelp(mediaTypes) {
  if (process.platform !== 'darwin' || mediaTypes.length === 0) {
    return;
  }

  const dialogKey = [...mediaTypes].sort().join(',');
  if (activePrivacyDialogs.has(dialogKey)) {
    return;
  }

  activePrivacyDialogs.add(dialogKey);

  try {
    const permissionNames = mediaTypes
      .map((mediaType) => macPrivacyLabels[mediaType])
      .join('、');
    const options = {
      type: 'warning',
      title: '需要系统权限',
      message: `无法访问${permissionNames}`,
      detail:
        `请在“系统设置 → 隐私与安全性”中允许本应用访问${permissionNames}，然后完全退出并重新打开应用。`,
      buttons: ['稍后', '打开系统设置'],
      defaultId: 1,
      cancelId: 0,
      noLink: true,
    };
    const result = mainWindow && !mainWindow.isDestroyed()
      ? await dialog.showMessageBox(mainWindow, options)
      : await dialog.showMessageBox(options);

    if (result.response === 1) {
      await openMacPrivacySettings(mediaTypes);
    }
  } finally {
    activePrivacyDialogs.delete(dialogKey);
  }
}

async function showLinuxScreenShareHelp(error) {
  if (process.platform !== 'linux') {
    return;
  }

  const errorDetail = error instanceof Error
    ? `\n\n错误信息：${error.message}`
    : '';

  console.warn('[screen-share] showing in-page Linux help:', errorDetail);

  try {
    await showInPageDialog({
      type: 'warning',
      title: '无法共享屏幕',
      message: 'Linux 屏幕捕获服务不可用',
      detail:
        `Wayland 桌面需要 PipeWire、xdg-desktop-portal，以及与桌面环境匹配的 portal 后端（GTK、GNOME 或 KDE）。请安装或启动这些服务后重新打开应用。应用将继续运行。${errorDetail}`,
      buttons: ['知道了'],
      defaultId: 0,
      cancelId: 0,
    });
  } catch (helpError) {
    console.error(
      '[screen-share] failed to show in-page Linux help:',
      helpError,
    );
  }
}

async function ensureMacMediaPermissions() {
  if (process.platform !== 'darwin') {
    return;
  }

  const deniedMediaTypes = [];

  for (const mediaType of ['camera', 'microphone']) {
    try {
      let status = systemPreferences.getMediaAccessStatus(mediaType);

      if (status === 'not-determined') {
        const granted = await systemPreferences.askForMediaAccess(mediaType);
        status = granted
          ? 'granted'
          : systemPreferences.getMediaAccessStatus(mediaType);
      }

      console.log(`[media-permission] ${mediaType}:`, status);

      if (status === 'denied' || status === 'restricted') {
        deniedMediaTypes.push(mediaType);
      }
    } catch (error) {
      console.error(`[media-permission] ${mediaType} request failed:`, error);
      deniedMediaTypes.push(mediaType);
    }
  }

  console.log(
    '[media-permission] screen:',
    systemPreferences.getMediaAccessStatus('screen'),
  );

  await showMacPrivacyHelp(deniedMediaTypes);
}

function markLocalRecordingCaptureRequest() {
  localRecordingCaptureRequestExpiresAt = Date.now() + 5000;
}

function consumeLocalRecordingCaptureRequest() {
  if (Date.now() > localRecordingCaptureRequestExpiresAt) {
    localRecordingCaptureRequestExpiresAt = 0;
    return false;
  }

  localRecordingCaptureRequestExpiresAt = 0;
  return true;
}

function getMainWindowCaptureSource(sources) {
  const windowSources = sources.filter((source) =>
    source.id.startsWith('window:'),
  );
  const mainTitle = mainWindow && !mainWindow.isDestroyed()
    ? mainWindow.getTitle()
    : '';

  if (mainTitle) {
    const titleMatchedSource = windowSources.find(
      (source) => source.name === mainTitle,
    );

    if (titleMatchedSource) {
      return titleMatchedSource;
    }
  }

  return windowSources[0] || sources.find((source) =>
    source.id.startsWith('screen:'),
  );
}

function setupScreenSharePermission(targetSession = session.defaultSession) {
  targetSession.setDisplayMediaRequestHandler(
    async (request, callback) => {
      try {
        console.log('[screen-share] request:', {
          securityOrigin: request.securityOrigin,
          videoRequested: request.videoRequested,
          audioRequested: request.audioRequested,
          userGesture: request.userGesture,
          linuxDisplayBackend:
            process.platform === 'linux' ? 'auto' : undefined,
        });

        if (process.platform === 'darwin') {
          const screenStatus = systemPreferences.getMediaAccessStatus('screen');
          console.log('[screen-share] macOS permission:', screenStatus);

          if (screenStatus === 'denied' || screenStatus === 'restricted') {
            await showMacPrivacyHelp(['screen']);
            callback({});
            return;
          }
        }

        const sources = await desktopCapturer.getSources({
          types: ['screen', 'window'],
          thumbnailSize: {
            width: 360,
            height: 220,
          },
          fetchWindowIcons: true,
        });

        console.log(
          '[screen-share] sources:',
          sources.map((source) => ({
            id: source.id,
            name: source.name,
          })),
        );

        if (!sources || sources.length === 0) {
          console.error('[screen-share] no screen/window sources found');

          if (process.platform === 'darwin') {
            const screenStatus = systemPreferences.getMediaAccessStatus('screen');
            if (screenStatus !== 'granted') {
              await showMacPrivacyHelp(['screen']);
            }
          } else if (process.platform === 'linux') {
            callback({});
            await showLinuxScreenShareHelp();
            return;
          }

          callback({});
          return;
        }

        if (consumeLocalRecordingCaptureRequest()) {
          const selectedSource = getMainWindowCaptureSource(sources);

          if (!selectedSource) {
            console.error('[local-recording] no capture source found');
            callback({});
            return;
          }

          console.log('[local-recording] selected:', {
            id: selectedSource.id,
            name: selectedSource.name,
          });

          callback({
            video: selectedSource,
          });
          return;
        }

        const selectedSource = await showScreenSourcePicker(sources);

        if (!selectedSource) {
          console.log('[screen-share] user cancelled');
          setScreenAnnotationCaptureSource(null);
          callback({});
          return;
        }

        console.log('[screen-share] selected:', {
          id: selectedSource.id,
          name: selectedSource.name,
        });

        setScreenAnnotationCaptureSource(selectedSource);
        callback({
          video: selectedSource,
        });
      } catch (error) {
        console.error('[screen-share] failed:', error);
        callback({});
        await showLinuxScreenShareHelp(error);
      }
    },
    {
      useSystemPicker: false,
    },
  );
}

function showScreenSourcePicker(sources) {
  return new Promise((resolve) => {
    let resolved = false;

    const pickerWindow = new BrowserWindow({
      width: 900,
      height: 620,
      title: '选择共享内容',
      parent: mainWindow || undefined,
      modal: Boolean(mainWindow),
      resizable: false,
      minimizable: false,
      maximizable: false,
      fullscreenable: false,
      backgroundColor: '#ffffff',
      webPreferences: {
        contextIsolation: true,
        nodeIntegration: false,
        sandbox: true,
      },
    });

    pickerWindow.setMenuBarVisibility(false);

    const safeSources = sources.map((source, index) => {
      let type = '窗口';

      if (source.id.startsWith('screen:')) {
        type = '屏幕';
      }

      return {
        index,
        id: source.id,
        name: source.name || `${type} ${index + 1}`,
        type,
        thumbnail: source.thumbnail
          ? source.thumbnail.toDataURL()
          : '',
      };
    });

    const html = `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <title>选择共享内容</title>
  <style>
    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Microsoft YaHei", sans-serif;
      background: #f5f6f8;
      color: #1f2937;
    }

    .header {
      height: 64px;
      padding: 0 24px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      background: #ffffff;
      border-bottom: 1px solid #e5e7eb;
    }

    .title {
      font-size: 18px;
      font-weight: 600;
    }

    .subtitle {
      margin-top: 4px;
      font-size: 12px;
      color: #6b7280;
    }

    .close {
      border: none;
      background: transparent;
      font-size: 24px;
      line-height: 1;
      cursor: pointer;
      color: #6b7280;
    }

    .tabs {
      display: flex;
      gap: 8px;
      padding: 16px 24px 0;
    }

    .tab {
      padding: 8px 18px;
      border-radius: 999px;
      border: 1px solid #d6e4ff;
      background: #ffffff;
      cursor: pointer;
      font-size: 14px;
      color: #1f2937;
      transition: all 0.15s ease;
    }

    .tab:hover {
      color: #1677ff;
      border-color: #1677ff;
    }

    .tab.active {
      color: #ffffff;
      background: #1677ff;
      border-color: #1677ff;
      box-shadow: 0 4px 10px rgba(22, 119, 255, 0.22);
    }

    .grid {
      padding: 20px 24px 24px;
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 16px;
      max-height: 455px;
      overflow-y: auto;
    }

    .card {
      border: 2px solid transparent;
      border-radius: 12px;
      background: #ffffff;
      overflow: hidden;
      cursor: pointer;
      transition: all 0.15s ease;
      box-shadow: 0 2px 8px rgba(15, 23, 42, 0.08);
    }

    .card:hover {
      transform: translateY(-2px);
      border-color: #1677ff;
      box-shadow: 0 8px 20px rgba(22, 119, 255, 0.18);
    }

    .thumb-wrap {
      height: 145px;
      background: #111827;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .thumb {
      max-width: 100%;
      max-height: 100%;
      object-fit: contain;
    }

    .info {
      padding: 12px;
    }

    .name {
      font-size: 14px;
      font-weight: 600;
      color: #111827;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    .type {
      margin-top: 6px;
      font-size: 12px;
      color: #6b7280;
    }

    .empty {
      padding: 60px;
      text-align: center;
      color: #6b7280;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="title">选择要共享的屏幕或窗口</div>
      <div class="subtitle">点击一个画面后立即开始共享</div>
    </div>
    <button class="close" onclick="cancelShare()">×</button>
  </div>

  <div class="tabs">
    <button class="tab active" data-filter="all" onclick="setFilter('all')">全部</button>
    <button class="tab" data-filter="屏幕" onclick="setFilter('屏幕')">屏幕</button>
    <button class="tab" data-filter="窗口" onclick="setFilter('窗口')">窗口</button>
  </div>

  <div id="grid" class="grid"></div>

  <script>
    const sources = ${JSON.stringify(safeSources)};
    let currentFilter = 'all';

    function render() {
      const grid = document.getElementById('grid');
      const filtered = sources.filter((source) => {
        if (currentFilter === 'all') return true;
        return source.type === currentFilter;
      });

      if (!filtered.length) {
        grid.innerHTML = '<div class="empty">没有可共享的内容</div>';
        return;
      }

      grid.innerHTML = filtered.map((source) => {
        return \`
          <div class="card" onclick="selectSource(\${source.index})" title="\${escapeHtml(source.name)}">
            <div class="thumb-wrap">
              <img class="thumb" src="\${source.thumbnail}" />
            </div>
            <div class="info">
              <div class="name">\${escapeHtml(source.name)}</div>
              <div class="type">\${source.type}</div>
            </div>
          </div>
        \`;
      }).join('');
    }

    function setFilter(filter) {
      currentFilter = filter;

      document.querySelectorAll('.tab').forEach((tab) => {
        tab.classList.toggle('active', tab.dataset.filter === filter);
      });

      render();
    }

    function selectSource(index) {
      window.location.href = 'screen-picker://select/' + index;
    }

    function cancelShare() {
      window.location.href = 'screen-picker://cancel';
    }

    function escapeHtml(value) {
      return String(value)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
    }

    render();
  </script>
</body>
</html>
`;

    pickerWindow.webContents.setWindowOpenHandler(() => {
      return { action: 'deny' };
    });

    pickerWindow.webContents.on('will-navigate', (event, url) => {
      if (!url.startsWith('screen-picker://')) {
        return;
      }

      event.preventDefault();

      if (url.startsWith('screen-picker://select/')) {
        const indexText = url.replace('screen-picker://select/', '');
        const index = Number(indexText);
        const selectedSource = sources[index];

        if (!resolved) {
          resolved = true;
          resolve(selectedSource || null);
        }

        if (!pickerWindow.isDestroyed()) {
          pickerWindow.close();
        }

        return;
      }

      if (url === 'screen-picker://cancel') {
        if (!resolved) {
          resolved = true;
          resolve(null);
        }

        if (!pickerWindow.isDestroyed()) {
          pickerWindow.close();
        }
      }
    });

    pickerWindow.on('closed', () => {
      if (!resolved) {
        resolved = true;
        resolve(null);
      }
    });

    pickerWindow.loadURL(
      'data:text/html;charset=utf-8,' + encodeURIComponent(html),
    );
  });
}

/**
 * 处理摄像头、麦克风、屏幕捕获等权限。
 */
function isTrustedAppUrl(value) {
  if (!value) {
    return false;
  }

  try {
    const url = new URL(value);
    const isLocalPage =
      url.hostname === '127.0.0.1' ||
      url.hostname === 'localhost';
    const upstream = new URL(serverUrl);
    const isAdminApi = url.hostname === upstream.hostname;

    return isLocalPage || isAdminApi;
  } catch {
    return false;
  }
}

function setupMediaPermission(targetSession = session.defaultSession) {
  targetSession.setPermissionRequestHandler(
    (webContents, permission, callback, details) => {
      const requestingUrl = details && details.requestingUrl
        ? details.requestingUrl
        : '';
      const securityOrigin = details && 'securityOrigin' in details
        ? details.securityOrigin
        : '';

      console.log('[permission-request]', {
        permission,
        requestingUrl,
        securityOrigin,
      });

      const allowedPermissions = new Set([
        'media',
        'display-capture',
        'clipboard-sanitized-write',
        'fullscreen',
        'pointerLock',
      ]);

      if (!allowedPermissions.has(permission)) {
        callback(false);
        return;
      }

      const originCandidates = [requestingUrl, securityOrigin].filter(Boolean);

      if (originCandidates.length === 0 && webContents) {
        originCandidates.push(webContents.getURL());
      }

      callback(originCandidates.some(isTrustedAppUrl));
    },
  );

  targetSession.setPermissionCheckHandler(
    (webContents, permission, requestingOrigin, details) => {
      console.log('[permission-check]', {
        permission,
        requestingOrigin,
        requestingUrl: details.requestingUrl,
        securityOrigin: details.securityOrigin,
      });

      const allowedPermissions = new Set([
        'media',
        'display-capture',
        'clipboard-sanitized-write',
        'fullscreen',
        'pointerLock',
      ]);

      if (!allowedPermissions.has(permission)) {
        return false;
      }

      const originCandidates = [
        requestingOrigin,
        details.requestingUrl,
        details.securityOrigin,
      ].filter(Boolean);

      if (originCandidates.length === 0 && webContents) {
        originCandidates.push(webContents.getURL());
      }

      return originCandidates.some(isTrustedAppUrl);
    },
  );
}

async function createWindow() {
  const port = await startLocalServer();
  setScreenAnnotationOverlayOrigin(`http://127.0.0.1:${port}`);
  const windowIconPath = resolveAssetPath('favicon.png');

  log.info('[window] icon:', {
    path: windowIconPath,
    exists: fs.existsSync(windowIconPath),
  });

  mainWindow = new BrowserWindow({
    width: 1366,
    height: 850,
    minWidth: 1100,
    minHeight: 720,
    title: appName,
    icon: windowIconPath,

    // 去掉顶部 File Edit View Window 菜单栏
    autoHideMenuBar: true,

    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  mainWindow.setMenuBarVisibility(false);
  mainWindow.removeMenu();

  if (process.platform === 'linux') {
    mainWindow.setIcon(windowIconPath);
  }

  /**
   * 关键：
   * 权限一定要绑定到当前窗口实际使用的 session 上。
   */
  setupScreenSharePermission(mainWindow.webContents.session);
  setupMediaPermission(mainWindow.webContents.session);

  mainWindow.setTitle(appName);

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    const targetUrl = new URL(url);
    const localAppOrigin = `http://127.0.0.1:${port}`;

    if (
      targetUrl.origin === localAppOrigin &&
      ['/api/auth/sso/start', '/im/index.html'].includes(targetUrl.pathname)
    ) {
      openInstantMessagingWindow(url, windowIconPath);
      return { action: 'deny' };
    }

    shell.openExternal(url);
    return { action: 'deny' };
  });

  /**
   * 开发环境打开 DevTools，方便查看 [screen-share] 日志。
   * 打包后不会自动打开。
   */
  if (isDev) {
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  }

  mainWindow.on('closed', () => {
    stopScreenAnnotationOverlay();
    if (instantMessagingWindow && !instantMessagingWindow.isDestroyed()) {
      instantMessagingWindow.close();
    }
    mainWindow = null;
  });

  await mainWindow.loadURL(`http://127.0.0.1:${port}/`);
}

function openInstantMessagingWindow(url, windowIconPath) {
  if (instantMessagingWindow && !instantMessagingWindow.isDestroyed()) {
    if (instantMessagingWindow.isMinimized()) {
      instantMessagingWindow.restore();
    }
    instantMessagingWindow.focus();
    return;
  }

  instantMessagingWindow = new BrowserWindow({
    width: 1280,
    height: 820,
    minWidth: 900,
    minHeight: 600,
    title: '即时通讯',
    icon: windowIconPath,
    autoHideMenuBar: true,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  instantMessagingWindow.setMenuBarVisibility(false);
  instantMessagingWindow.removeMenu();

  if (process.platform === 'linux') {
    instantMessagingWindow.setIcon(windowIconPath);
  }

  instantMessagingWindow.webContents.setWindowOpenHandler(({ url: targetUrl }) => {
    shell.openExternal(targetUrl);
    return { action: 'deny' };
  });

  instantMessagingWindow.on('closed', () => {
    instantMessagingWindow = null;
  });

  instantMessagingWindow.loadURL(url).catch((error) => {
    log.error('[instant-messaging] failed to load:', error);
  });
}

async function startLocalServer() {
  const distDir = getDistDir();
  const port = await getFreePort();
  const localOrigin = `http://127.0.0.1:${port}`;

  server = http.createServer((req, res) => {
    if (!req.url || !req.method) {
      res.writeHead(400);
      res.end();
      return;
    }

    if (
      req.url.startsWith('/api/') ||
      req.url.startsWith('/uploads/') ||
      req.url.startsWith('/downloads/')
    ) {
      proxyRequest(req, res);
      return;
    }

    if (
      req.method === 'POST' &&
      req.url.startsWith('/__uniccmeet/electron/local-recording-capture')
    ) {
      markLocalRecordingCaptureRequest();
      res.writeHead(204);
      res.end();
      return;
    }

    if (req.url.startsWith('/__uniccmeet/electron/screen-annotation/')) {
      const requestOrigin = req.headers.origin || (() => {
        try {
          return req.headers.referer
            ? new URL(req.headers.referer).origin
            : '';
        } catch {
          return '';
        }
      })();
      if (requestOrigin !== localOrigin) {
        res.writeHead(403);
        res.end();
        return;
      }
      void handleScreenAnnotationRequest(req, res);
      return;
    }

    serveStatic(distDir, req, res);
  });

  await new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(port, '127.0.0.1', resolve);
  });

  console.log(`[local-server] started: http://127.0.0.1:${port}/`);

  return port;
}

function getDistDir() {
  if (isDev) {
    return path.join(__dirname, '..', 'dist');
  }

  return path.join(process.resourcesPath, 'dist');
}

function resolveAssetPath(fileName) {
  if (isDev) {
    return path.join(__dirname, '..', 'src', 'assets', fileName);
  }

  return path.join(process.resourcesPath, 'app-icon.png');
}

function serveStatic(root, req, res) {
  let requestURL;
  let pathname;

  try {
    requestURL = new URL(req.url, 'http://127.0.0.1');
    pathname = decodeURIComponent(requestURL.pathname);
  } catch {
    res.writeHead(400);
    res.end();
    return;
  }

  const normalizedPath = path.normalize(pathname).replace(/^(\.\.[/\\])+/, '');
  let filePath = path.join(root, normalizedPath);

  if (!filePath.startsWith(root)) {
    res.writeHead(403);
    res.end();
    return;
  }

  if (pathname === '/meet' || pathname.startsWith('/meet/')) {
    const maybeFile = filePath;

    filePath =
      fs.existsSync(maybeFile) && fs.statSync(maybeFile).isFile()
        ? maybeFile
        : path.join(root, 'meet', 'index.html');
  } else if (!fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) {
    filePath = path.join(root, 'index.html');
  }

  fs.readFile(filePath, (err, data) => {
    if (err) {
      console.error('[static] file read failed:', filePath, err);
      res.writeHead(404);
      res.end();
      return;
    }

    res.writeHead(200, {
      'Content-Type': contentType(filePath),
    });

    res.end(data);
  });
}

function proxyRequest(req, res) {
  let upstream;

  try {
    upstream = new URL(req.url, serverUrl);
  } catch {
    res.writeHead(400, {
      'Content-Type': 'application/json; charset=utf-8',
    });
    res.end(JSON.stringify({ error: 'invalid upstream url' }));
    return;
  }

  const transport = upstream.protocol === 'https:' ? https : http;

  const headers = {
    ...req.headers,
    host: upstream.host,
  };

  /**
   * 避免部分代理压缩响应导致 Electron 本地代理处理异常。
   */
  delete headers['accept-encoding'];

  const proxy = transport.request(
    upstream,
    {
      method: req.method,
      headers,
    },
    (proxyRes) => {
      res.writeHead(proxyRes.statusCode || 502, proxyRes.headers);
      proxyRes.pipe(res);
    },
  );

  proxy.on('error', (error) => {
    console.error('[proxy] admin api unavailable:', error);

    res.writeHead(502, {
      'Content-Type': 'application/json; charset=utf-8',
    });

    res.end(JSON.stringify({ error: 'admin api unavailable' }));
  });

  req.pipe(proxy);
}

function contentType(filePath) {
  const ext = path.extname(filePath).toLowerCase();

  const types = {
    '.html': 'text/html; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.mjs': 'text/javascript; charset=utf-8',
    '.css': 'text/css; charset=utf-8',
    '.json': 'application/json; charset=utf-8',
    '.png': 'image/png',
    '.ico': 'image/x-icon',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.svg': 'image/svg+xml',
    '.webp': 'image/webp',
    '.gif': 'image/gif',
    '.wasm': 'application/wasm',
    '.map': 'application/json; charset=utf-8',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
    '.ttf': 'font/ttf',
  };

  return types[ext] || 'application/octet-stream';
}

function getFreePort() {
  return new Promise((resolve, reject) => {
    const tester = net.createServer();

    tester.once('error', reject);

    tester.listen(0, '127.0.0.1', () => {
      const address = tester.address();

      tester.close(() => {
        if (!address || typeof address === 'string') {
          reject(new Error('failed to get free port'));
          return;
        }

        resolve(address.port);
      });
    });
  });
}

app.whenReady().then(async () => {
  Menu.setApplicationMenu(null);
  await createWindow();
  await ensureMacMediaPermissions();
  setupAutoUpdater();
});

app.on('window-all-closed', () => {
  stopScreenAnnotationOverlay();
  if (server) {
    server.close(() => {
      console.log('[local-server] closed');
    });

    server = null;
  }

  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('before-quit', () => {
  if (updateCheckTimer) {
    clearInterval(updateCheckTimer);
    updateCheckTimer = null;
  }

  if (server) {
    server.close();
    server = null;
  }
});
